name: C++ Insights Gitpod Builder Image CI

on:
  push:
    branches: [main]

  repository_dispatch:
    types: [rebuild_trigger]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
            make build
            docker images

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u andreasfertig --password-stdin

      - name: Push the tagged Docker image
        run: |
            docker tag andreasfertig/cppinsights-builder-gitpod andreasfertig/cppinsights-builder-gitpod
            docker push andreasfertig/cppinsights-builder-gitpod
