name: C++ Insights Gitpod Builder Image CI

on:
  push:
    branches: [main]

  repository_dispatch:
    types: [rebuild_trigger]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
        name: Set up QEMU

      - uses: docker/setup-buildx-action@v3
        name: Set up Docker Buildx

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u andreasfertig --password-stdin

      - name: Build the Docker image
        run: |
            make buildpush
            docker images

